/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1005108;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author BulBul
 */
public class MST extends javax.swing.JFrame {

    /**
     * Creates new form MST
     */
    JLabel[] label;
    ImageIcon blank;
    int NoofNode=0;
    int[] posx;
    int[] posy;
    int[] from;
    int[] to;
    
    public MST(int No) {
        NoofNode=No;
        posx=new int[No];
        posy=new int[No];
        from=new int[No+1];
        to=new int[No+1];
        initComponents();
        setVisible(true);
        label=new JLabel[No];
        blank = new ImageIcon("1005108.png");
    }

    public void DrawNode(int i,int x,int y){
        label[i] = new JLabel();
        label[i].setIcon(blank);
        label[i].setBounds(x, y,40,40);
        this.add(label[i]);
        posx[i]=x+20;
        posy[i]=y+40;
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);  // fixes the immediate problem.
        Graphics2D g2 = (Graphics2D) g;
        int i;
        for(i=0;i<NoofNode+1;i++){
            Line2D lin = new Line2D.Float(posx[from[i]], posy[from[i]], posx[to[i]], posy[to[i]]);
            g2.setColor(Color.GREEN);
            g2.setStroke(new BasicStroke(4f));
            g2.draw(lin);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
